spring:
  datasource:
    url: jdbc:mysql://rm-bp196027c6l4cnh7vho.mysql.rds.aliyuncs.com:3306/SecurityDemo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/SecurityDemo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: swb
#    username: root
    password: Qaz840068536
#    password: swb1027495836
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8081
  servlet:
    session:
      timeout: 30M
mapper:
  #公用接口类路径,不能与
  mappers: com.swb.security.demo.dao.MyMapper
  identity: MYSQL
mybatis:
  type-aliases-package: com.swb.security.demo.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com:
      swb:
        security:
          demo:
            mapper: debug
  file:
    name: ./security-demo/out/log/demo.log
    max-size: 5MB
filePath: D:/MY/IDEA/security-gradle/security-demo/out/file/
#swb:
#  security:
#    browser:
#      loginType: JSON
#    validateCode:
#      imageCode:
#        length: 5
#        width: 300
#        url: /user/*