spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SecurityDemo?serverTimezone=Shanghai&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
mapper:
  #公用接口类路径,不能与
  mappers: com.swb.security.demo.dao.IBaseDao
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com:
      weige:
        springboot:
          mapper: debug
  file:
    name: ./security-demo/out/log/demo.log
    max-size: 5MB
filePath: D:/MY/IDEA/security-gradle/security-demo/out/file/
swb.security.browser.loginPage: /demoLogin.html
swb.security.browser.loginType: REDIRECT